INSERT INTO projects (
    titre,
    resume_ai,
    montant_mad,
    secteur,
    region,
    porteur,
    stade,
    date_annonce,
    sources,
    nb_sources_confirmees,
    latitude,
    longitude,
    score_fiabilite,
    score_details
)
VALUES
(
    'Extension industrielle automobile à Kénitra',
    'Projet industriel visant à renforcer la capacité de production automobile dans la région Rabat-Salé-Kénitra.',
    2500000000,
    'Industrie',
    'Rabat-Salé-Kénitra',
    'Groupe automobile international',
    'en_cours',
    '2025-04-20',
    '[{"name":"AMDIE","url":"https://www.amdie.gov.ma","niveau":1},{"name":"Médias24","url":"https://medias24.com","niveau":3}]',
    2,
    34.0209,
    -6.8416,
    82,
    '{"score_niveau_source":100,"score_triangulation":70,"score_precision_montant":60,"score_fraicheur":80,"score_llm":90}'
),
(
    'Projet solaire régional à Ouarzazate',
    'Projet énergétique solaire destiné à augmenter la production d’énergie renouvelable.',
    4200000000,
    'Énergie',
    'Drâa-Tafilalet',
    'MASEN',
    'annoncé',
    '2025-05-12',
    '[{"name":"Ministère de l Energie","url":"https://www.mcinet.gov.ma","niveau":2}]',
    1,
    31.9314,
    -4.4339,
    74,
    '{"score_niveau_source":80,"score_triangulation":30,"score_precision_montant":60,"score_fraicheur":100,"score_llm":85}'
),
(
    'Plateforme logistique à Tanger Med',
    'Développement d’une plateforme logistique pour accompagner les flux industriels et portuaires.',
    1800000000,
    'Logistique',
    'Tanger-Tétouan-Al Hoceïma',
    'Tanger Med',
    'finalisé',
    '2024-11-02',
    '[{"name":"CRI Tanger","url":"https://tangerinvest.ma","niveau":1},{"name":"Le Matin","url":"https://lematin.ma","niveau":3}]',
    2,
    35.7595,
    -5.8340,
    86,
    '{"score_niveau_source":100,"score_triangulation":70,"score_precision_montant":60,"score_fraicheur":80,"score_llm":95}'
);